name: telco_churn_ci_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - setuptools<81
      - mlflow==3.14.0
      - pandas
      - numpy
      - scikit-learn
      - joblib